name: Java Build and Release

on:
  push:
    tags:
      - 'v*'  # 触发构建和发布的标签模式

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Grant execute permission for build-java.sh
        run: chmod +x ./build-java.sh

      - name: Run build script
        run: ./build-java.sh

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "rasp-java.tar.gz,rasp-java.zip"
          generateReleaseNotes: true
          skipIfReleaseExists: true
          bodyFile: "release.md"

# 创建一个标签
#   git tag v1.3.7
# 推送标签到 GitHub
#   git push origin v1.3.7
# 列出所有本地标签：
#   git tag
# 删除指定标签
#   git tag -d [标签名]
